### ISSUE TITLE
Secure password hashing and comparison

### ISSUE THREAD

**Issue by astei** [mikroskeem/depot#7]
Insecure comparison: https://github.com/mikroskeem/depot/blob/master/server.go#L184

Insecure storage: https://github.com/mikroskeem/depot/blob/master/config.sample.toml#L25

I suggest using [golang.org/x/crypto/argon2](https://pkg.go.dev/golang.org/x/crypto/argon2?tab=doc) and [double HMAC](https://www.nccgroup.com/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/) to fix these problems.

**Comment by astei** [comment]
See #8, the "official" issue.

**Comment by mikroskeem** [comment]
Damn timing! 😄
